const $ = (id) => document.getElementById(id);
let state = { gallery: [] };
function setStatus(text, good = true) { const el = $('status'); el.textContent = text; el.style.color = good ? '#7ff0ae' : '#ff9c9c'; }
async function load() { const res = await fetch('/api/content'); state = await res.json(); $('siteName').value = state.siteName || ''; $('tagline').value = state.tagline || ''; $('description').value = state.description || ''; $('phone').value = state.phone || ''; renderGallery(); }
function renderGallery() { const box = $('gallery'); box.innerHTML = ''; if (!state.gallery?.length) { box.innerHTML = '<p class="hint">لم تتم إضافة صور مخصصة بعد.</p>'; return; } state.gallery.forEach((item, index) => { const card = document.createElement('article'); card.className = 'gallery-card'; card.innerHTML = `<button class="remove" data-index="${index}" type="button">حذف</button><img src="${item.url}" alt=""><p>${item.name}</p>`; box.appendChild(card); }); }
$('settingsForm').addEventListener('submit', async (e) => { e.preventDefault(); state = { ...state, siteName: $('siteName').value.trim(), tagline: $('tagline').value.trim(), description: $('description').value.trim(), phone: $('phone').value.trim() }; const res = await fetch('/api/content', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(state) }); setStatus(res.ok ? 'تم الحفظ بنجاح' : 'تعذر الحفظ', res.ok); });
$('imageInput').addEventListener('change', async (e) => { for (const file of e.target.files) { const data = await new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); const res = await fetch('/api/upload', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ name:file.name, type:file.type, data }) }); if (res.ok) { const result = await res.json(); state.gallery.push(result.item); } } e.target.value = ''; renderGallery(); setStatus('تمت إضافة الصور'); });
$('gallery').addEventListener('click', async (e) => { const btn = e.target.closest('.remove'); if (!btn) return; const index = Number(btn.dataset.index); if (!confirm('حذف هذه الصورة؟')) return; await fetch(`/api/gallery/${index}`, { method:'DELETE' }); state.gallery.splice(index, 1); renderGallery(); setStatus('تم حذف الصورة'); });
load().catch(() => setStatus('شغّل server.js أولًا', false));
