const OWNER='tonysyds28-dot', REPO='volt-pro-website', BRANCH='main';
let token=sessionStorage.getItem('poppro_github_token')||'', current=null, files=[];
const $=id=>document.getElementById(id); const api=(path,opts={})=>fetch(`https://api.github.com${path}`,{...opts,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,...(opts.headers||{})}}); const filePath=p=>p.split('/').map(encodeURIComponent).join('/');
function setConnected(on){$('connectionText').textContent=on?'متصل بـ GitHub':'غير متصل';$('connectionDot').parentElement.classList.toggle('connected',on);$('connectPanel').classList.toggle('hidden',on);$('app').classList.toggle('hidden',!on);$('disconnect').classList.toggle('hidden',!on);}
async function connect(){try{const r=await api('/user');if(!r.ok)throw new Error('المفتاح غير صحيح أو منتهي'); sessionStorage.setItem('poppro_github_token',token);setConnected(true);await loadFiles();}catch(e){alert(e.message);setConnected(false);}}
async function loadFiles(){const r=await api(`/repos/${OWNER}/${REPO}/git/trees/${BRANCH}?recursive=1`);if(!r.ok)throw new Error('تعذر قراءة ملفات المستودع');const data=await r.json();files=data.tree.filter(x=>x.type==='blob'&&!x.path.startsWith('.git/'));renderFiles();}
function renderFiles(){const box=$('fileList');box.innerHTML='';files.forEach(f=>{const b=document.createElement('button');b.className='file';b.dataset.path=f.path;b.innerHTML=`<span class="type">${icon(f.path)}</span><span>${f.path}</span>`;b.onclick=()=>openFile(f);box.appendChild(b);});}
function icon(p){if(/\.(jpg|jpeg|png|webp|gif)$/i.test(p))return'▧';if(/\.css$/i.test(p))return'◈';if(/\.js$/i.test(p))return'◉';if(/\.html?$/i.test(p))return'◇';return'□';}
async function openFile(file){const r=await api(`/repos/${OWNER}/${REPO}/contents/${filePath(file.path)}?ref=${BRANCH}`);if(!r.ok)return alert('تعذر قراءة الملف');const d=await r.json();current={...file,sha:d.sha,encoding:d.encoding};$('fileName').textContent=file.path;$('editor').value=d.encoding==='base64'?decodeURIComponent(escape(atob(d.content.replaceAll('\n','')))):d.content;$('save').disabled=false;$('delete').disabled=false;document.querySelectorAll('.file').forEach(x=>x.classList.toggle('active',x.dataset.path===file.path));}
async function saveFile(){if(!current)return;const content=btoa(unescape(encodeURIComponent($('editor').value)));const r=await api(`/repos/${OWNER}/${REPO}/contents/${filePath(current.path)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:$('commitMessage').value||'Update from Pop Pro Admin',content,sha:current.sha,branch:BRANCH})});if(!r.ok){const e=await r.json();return alert(e.message||'فشل الحفظ');}const d=await r.json();current.sha=d.content.sha;$('saveStatus').textContent='تم الحفظ — Netlify سيعيد النشر تلقائيًا';setTimeout(()=>$('saveStatus').textContent='جاهز',5000);}
async function deleteFile(){if(!current||!confirm(`حذف ${current.path} نهائيًا من GitHub؟`))return;const r=await api(`/repos/${OWNER}/${REPO}/contents/${filePath(current.path)}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Delete ${current.path} from Pop Pro Admin`,sha:current.sha,branch:BRANCH})});if(!r.ok){const e=await r.json();return alert(e.message||'فشل حذف الملف');}current=null;$('fileName').textContent='اختر ملفًا';$('editor').value='';$('save').disabled=true;$('delete').disabled=true;await loadFiles();$('saveStatus').textContent='تم الحذف — Netlify سيعيد النشر تلقائيًا';}
async function createFile(){const path=prompt('اكتب مسار الملف الجديد، مثال: image/new.txt');if(!path)return;const content=prompt('اكتب محتوى الملف الجديد:','');if(content===null)return;const r=await api(`/repos/${OWNER}/${REPO}/contents/${filePath(path)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Create ${path} from Pop Pro Admin`,content:btoa(unescape(encodeURIComponent(content))),branch:BRANCH})});if(!r.ok){const e=await r.json();return alert(e.message||'فشل إنشاء الملف');}await loadFiles();alert('تم إنشاء الملف.');}
async function uploadImage(file){const reader=new FileReader();reader.onload=async()=>{const base64=reader.result.split(',')[1];const path=`image/uploads/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const r=await api(`/repos/${OWNER}/${REPO}/contents/${filePath(path)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Upload ${file.name} from Pop Pro Admin`,content:base64,branch:BRANCH})});if(!r.ok){const e=await r.json();return alert(e.message||'فشل رفع الصورة');}await loadFiles();alert('تم رفع الصورة إلى GitHub.');};reader.readAsDataURL(file);}
$('connectForm').onsubmit=e=>{e.preventDefault();token=$('token').value.trim();connect()};$('save').onclick=saveFile;$('delete').onclick=deleteFile;$('newFile').onclick=createFile;$('upload').onchange=e=>e.target.files[0]&&uploadImage(e.target.files[0]);$('disconnect').onclick=()=>{sessionStorage.removeItem('poppro_github_token');token='';setConnected(false)};if(token){setConnected(true);loadFiles().catch(e=>{alert(e.message);sessionStorage.removeItem('poppro_github_token');setConnected(false)})}else setConnected(false);
