const OWNER='tonysyds28-dot', REPO='volt-pro-website', BRANCH='main';
let token=sessionStorage.getItem('poppro_github_token')||'', files=[], current=null, projects=[];
const $=id=>document.getElementById(id); const api=(p,o={})=>fetch(`https://api.github.com${p}`,{...o,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,...(o.headers||{})}}); const pathOf=p=>p.split('/').map(encodeURIComponent).join('/');
function setConnected(on){$('connectionText').textContent=on?'متصل بـ GitHub':'غير متصل';$('connectionDot').parentElement.classList.toggle('connected',on);$('connectPanel').classList.toggle('hidden',on);$('app').classList.toggle('hidden',!on);$('disconnect').classList.toggle('hidden',!on);}
async function connect(){try{const r=await api('/user');if(!r.ok)throw Error('المفتاح غير صحيح أو لا يملك الصلاحية المطلوبة');sessionStorage.setItem('poppro_github_token',token);setConnected(true);await refresh();await loadContent();}catch(e){alert(e.message);setConnected(false)}}
async function refresh(){await loadFiles();buildProjects();renderProjects();}
async function loadFiles(){const r=await api(`/repos/${OWNER}/${REPO}/git/trees/${BRANCH}?recursive=1`);if(!r.ok)throw Error('تعذر قراءة المستودع');const d=await r.json();files=d.tree.filter(x=>x.type==='blob'&&!x.path.startsWith('.git/'));}
function buildProjects(){const imgs=files.filter(f=>/\.(jpg|jpeg|png|webp|gif)$/i.test(f.path));const group=(name,keys)=>imgs.filter(f=>keys.some(k=>f.path.toLowerCase().includes(k))).map(f=>f.path);projects=[{id:'under-construction',title:'مشروع تحت الإنشاء',description:'أعمال ومشاريع قيد التنفيذ',path:'image/projects/under-construction',images:group('factory',['factory'])},{id:'riyadh-club',title:'نادي الرياض - البنية التحتية',description:'مشروع تم تنفيذه',path:'image/projects/riyadh-club',images:group('riyadh',['riyadh'])},{id:'rehab-smart-home',title:'سمارت هوم - شقة الرحاب',description:'مشروع تم تنفيذه',path:'image/projects/rehab-smart-home',images:group('rehab',['rehab'])},{id:'sunrise-villa',title:'فيلا الشروق - التأسيس الكهربائي',description:'مشروع تم تنفيذه',path:'image/projects/sunrise-villa',images:group('sunrise',['sunrise'])}];const custom=files.filter(f=>f.path.startsWith('projects/')&&f.path.endsWith('README.md'));custom.forEach(f=>{const id=f.path.split('/')[1];if(!projects.some(p=>p.id===id))projects.push({id,title:id.replaceAll('-',' '),description:'مشروع مضاف حديثًا',path:`image/projects/${id}`,images:imgs.filter(i=>i.path.includes(`/projects/${id}/`)).map(i=>i.path)})});}
function renderProjects(){const box=$('projectGrid');box.innerHTML='';if(!projects.length){box.innerHTML='<div class="empty">لا توجد مشاريع بعد. أضف مشروعك الأول.</div>';return}projects.forEach(p=>{const card=document.createElement('article');card.className='project-card';const cover=p.images[0]?`<img src="https://raw.githubusercontent.com/${OWNER}/${REPO}/${BRANCH}/${p.images[0]}" alt="">`:'<span>✦</span>';card.innerHTML=`<div class="project-cover">${cover}</div><div class="project-body"><h3>${p.title}</h3><p>${p.description} · ${p.images.length} صور</p><div class="project-actions"><button data-upload="${p.id}">رفع صور</button><button class="outline" data-open="${p.id}">فتح المجلد</button></div></div>`;box.appendChild(card)});}
function uploadTo(project){const input=document.createElement('input');input.type='file';input.accept='image/*';input.multiple=true;input.onchange=()=>[...input.files].forEach(file=>uploadImage(file,project));input.click();}
async function uploadImage(file,project){const reader=new FileReader();reader.onload=async()=>{const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${project.path}/${Date.now()}-${safe}`;const r=await api(`/repos/${OWNER}/${REPO}/contents/${pathOf(path)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Add image to ${project.title}`,content:reader.result.split(',')[1],branch:BRANCH})});if(!r.ok){const e=await r.json();return alert(e.message||'فشل رفع الصورة')}await refresh();};reader.readAsDataURL(file);}
async function newProject(){const title=prompt('اسم المشروع:');if(!title)return;const description=prompt('وصف مختصر للمشروع:','مشروع جديد');if(description===null)return;const id=title.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`project-${Date.now()}`;const readme=`# ${title}\n\n${description}\n`;const r=await api(`/repos/${OWNER}/${REPO}/contents/projects/${id}/README.md`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Create project ${title}`,content:btoa(unescape(encodeURIComponent(readme))),branch:BRANCH})});if(!r.ok){const e=await r.json();return alert(e.message||'فشل إنشاء المشروع')}await refresh();alert('تم إنشاء المشروع. يمكنك الآن رفع الصور إليه.');}
$('projectGrid').onclick=e=>{const up=e.target.closest('[data-upload]'),open=e.target.closest('[data-open]');if(up){const p=projects.find(x=>x.id===up.dataset.upload);uploadTo(p)}if(open){const p=projects.find(x=>x.id===open.dataset.open);window.open(`https://github.com/${OWNER}/${REPO}/tree/${BRANCH}/${p.path}`,'_blank')}};
function renderFiles(){const box=$('fileList');box.innerHTML='';files.forEach(f=>{const b=document.createElement('button');b.className='file';b.textContent=f.path;b.onclick=()=>openFile(f);box.appendChild(b)})}
async function openFile(f){const r=await api(`/repos/${OWNER}/${REPO}/contents/${pathOf(f.path)}?ref=${BRANCH}`);if(!r.ok)return alert('تعذر قراءة الملف');const d=await r.json();current={...f,sha:d.sha};$('fileName').textContent=f.path;$('editor').value=d.encoding==='base64'?decodeURIComponent(escape(atob(d.content.replaceAll('\n','')))):d.content;$('save').disabled=false;$('delete').disabled=false;renderFiles()}
async function saveFile(){if(!current)return;const r=await api(`/repos/${OWNER}/${REPO}/contents/${pathOf(current.path)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:$('commitMessage').value||'Update from Pop Pro Admin',content:btoa(unescape(encodeURIComponent($('editor').value))),sha:current.sha,branch:BRANCH})});if(!r.ok){const e=await r.json();return alert(e.message||'فشل الحفظ')}current.sha=(await r.json()).content.sha;alert('تم الحفظ. سيبدأ Netlify النشر تلقائيًا.');}
async function deleteFile(){if(!current||!confirm(`حذف ${current.path} نهائيًا؟`))return;const r=await api(`/repos/${OWNER}/${REPO}/contents/${pathOf(current.path)}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Delete ${current.path}`,sha:current.sha,branch:BRANCH})});if(!r.ok){const e=await r.json();return alert(e.message||'فشل الحذف')}current=null;$('fileName').textContent='اختر ملفًا';$('editor').value='';$('save').disabled=true;$('delete').disabled=true;await refresh();}
async function createFile(){const p=prompt('مسار الملف الجديد:');if(!p)return;const c=prompt('محتوى الملف:','');if(c===null)return;const r=await api(`/repos/${OWNER}/${REPO}/contents/${pathOf(p)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Create ${p}`,content:btoa(unescape(encodeURIComponent(c))),branch:BRANCH})});if(!r.ok)return alert('فشل إنشاء الملف');await refresh();renderFiles()}
async function loadContent(){try{const r=await api(`/repos/${OWNER}/${REPO}/contents/content.json?ref=${BRANCH}`);if(!r.ok)return;const d=await r.json();const content=JSON.parse(decodeURIComponent(escape(atob(d.content.replaceAll('\n','')))));$('siteName').value=content.siteName||'Pop Pro';$('siteTagline').value=content.tagline||'';$('siteDescription').value=content.description||'';$('sitePhone').value=content.phone||'';}catch(e){console.warn('content load failed',e)}}
async function saveContent(){const status=$('contentStatus');status.textContent='جارٍ الحفظ…';try{const read=await api(`/repos/${OWNER}/${REPO}/contents/content.json?ref=${BRANCH}`);const existing=await read.json();const old=JSON.parse(decodeURIComponent(escape(atob(existing.content.replaceAll('\n','')))));const data={...old,siteName:$('siteName').value.trim(),tagline:$('siteTagline').value.trim(),description:$('siteDescription').value.trim(),phone:$('sitePhone').value.trim()};const r=await api(`/repos/${OWNER}/${REPO}/contents/content.json`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Update site content from Admin',content:btoa(unescape(encodeURIComponent(JSON.stringify(data,null,2)+'\n'))),sha:existing.sha,branch:BRANCH})});if(!r.ok){const error=await r.json();throw Error(`${r.status}: ${error.message||'GitHub رفض العملية'}`)}status.textContent='تم حفظ البيانات وسيعاد نشر الموقع تلقائيًا';}catch(e){status.textContent=`تعذر الحفظ: ${e.message}`;}}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.add('hidden'));t.classList.add('active');$(t.dataset.tab).classList.remove('hidden');if(t.dataset.tab==='advanced'){renderFiles()}});$('connectForm').onsubmit=e=>{e.preventDefault();token=$('token').value.trim();connect()};$('newProject').onclick=newProject;$('refresh').onclick=async()=>{await refresh();await loadContent()};$('save').onclick=saveFile;$('delete').onclick=deleteFile;$('newFile').onclick=createFile;$('saveContent').onclick=saveContent;$('disconnect').onclick=()=>{sessionStorage.removeItem('poppro_github_token');token='';setConnected(false)};if(token){setConnected(true);refresh().then(loadContent).catch(()=>{sessionStorage.removeItem('poppro_github_token');setConnected(false)})}else setConnected(false);
